export enum BatchMintStatus {
  CREATED_AND_WAITING_FOR_FEE = 'CREATED_AND_WAITING_FOR_FEE',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  REACHED_LOW_MINT_LIMIT = 'REACHED_LOW_MINT_LIMIT',
  ERROR = 'ERROR',
}
