export enum BatchMintStatus {
  CREATED_AND_WAITING_FOR_KAS = 'CREATED_AND_WAITING_FOR_KAS',
  WAITING_FOR_JOB = 'WAITING_FOR_JOB',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  ERROR = 'ERROR',
  POD_NOT_INITIALIZED_ERROR = 'POD_NOT_INITIALIZED_ERROR',
}
