export enum SellOrderStatusV2 {
  LISTED_FOR_SALE = 'LISTED_FOR_SALE',
  VERIFYING = 'VERIFYING',
  FAILED_VERIFICATION = 'FAILED_VERIFICATION',
  COMPLETED = 'COMPLETED',
  CANCELED = 'CANCELED',
  PSKT_VERIFICATION_ERROR = 'PSKT_VERIFICATION_ERROR',
}
