export enum SellOrderStatus {
  WAITING_FOR_TOKENS = 'WAITING_FOR_TOKENS',
  LISTED_FOR_SALE = 'LISTED_FOR_SALE',
  WAITING_FOR_KAS = 'WAITING_FOR_KAS',
  CHECKOUT = 'CHECKOUT',
  COMPLETED = 'COMPLETED',
  CANCELED = 'CANCELED',
  SWAP_ERROR = 'SWAP_ERROR',

  // DELIST FLOW
  DELIST_WAITING_FOR_KAS = 'DELIST_WAITING_FOR_KAS',
  DELISTING = 'DELISTING',
  DELIST_ERROR = 'DELIST_ERROR',
  COMPLETED_DELISTING = 'COMPLETED_DELISTING',
}
