export enum SellOrderStatus {
    WAITING_FOR_TOKENS = 'WAITING_FOR_TOKENS',
    LISTED_FOR_SALE = 'LISTED_FOR_SALE',
    WAITING_FOR_KAS = 'WAITING_FOR_KAS',
    CHECKOUT = 'CHECKOUT',
    COMPLETED = 'COMPLETED',
}