name: Deploy Node.js Application to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set Up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify your Node.js version

    - name: Install Dependencies
      run: npm install

    # - name: Run Tests
    #   run: npm test

    - name: Build Application
      run: npm run build  # Adjust if you have a build step

    - name: Create Application Package
      run: |
        zip -r deploy.zip *  # Create a ZIP file of the application

    - name: Retrieve Counter from S3
      id: get_counter
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        aws s3 cp s3://elasticbeanstalk-us-east-1-009160070963/counter.txt counter.txt --region $AWS_REGION || echo "0" > counter.txt
        COUNTER=$(cat counter.txt)
        echo "Current counter: $COUNTER"
        echo "COUNTER=$COUNTER" >> $GITHUB_ENV

    - name: Increment Counter
      id: increment_counter
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        COUNTER=$(($COUNTER + 1))
        echo $COUNTER > counter.txt
        aws s3 cp counter.txt s3://elasticbeanstalk-us-east-1-009160070963/counter.txt --region $AWS_REGION
        echo "Incremented counter: $COUNTER"
        echo "NEW_COUNTER=$COUNTER" >> $GITHUB_ENV

    - name: Upload Package to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        NEW_COUNTER: ${{ env.NEW_COUNTER }}
      run: |
        aws s3 cp deploy.zip s3://elasticbeanstalk-us-east-1-009160070963/deploy-trade-server-${{ github.run_number }}-${{ env.NEW_COUNTER }}.zip --region $AWS_REGION

    - name: Deploy to Elastic Beanstalk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        NEW_COUNTER: ${{ env.NEW_COUNTER }}
      run: |
        VERSION_LABEL="v${{ github.run_number }}-${{ env.NEW_COUNTER }}-${{ github.sha }}"
        
        aws elasticbeanstalk create-application-version \
            --application-name kaspiano \
            --version-label ${VERSION_LABEL} \
            --source-bundle S3Bucket=elasticbeanstalk-us-east-1-009160070963,S3Key=deploy-trade-server-${{ github.run_number }}-${{ env.NEW_COUNTER }}.zip \
            --region $AWS_REGION
        
        aws elasticbeanstalk update-environment \
            --environment-name p2p-trade-service \
            --version-label ${VERSION_LABEL} \
            --region $AWS_REGION
